/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Controladora_Pedidos;
import java.util.ArrayList;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Entidades.Pedido;
import model.modeloTabela.ModeloTabela;
/**
 *
 * @author Victor
 */
public class Tela_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Funcionario
     */
    public Tela_Funcionario(String NomeFuncionario, String  filtro) {
        initComponents();
        NomedoFuncionario.setText(NomeFuncionario);
        if(filtro.equals("")){
            filtroPor.setText("Mostrando Todos os Pedidos");
        }
        if(filtro.equals("ABERTO")){
            filtroPor.setText("Filtrado por Aberto");
        }
        if(filtro.equals("Pago")){
            filtroPor.setText("Filtrado por Pago");
        }        
        carregarTabela(filtro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        NomedoFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Pedidos = new javax.swing.JTable();
        Logout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Pago = new javax.swing.JButton();
        FiltroPago = new javax.swing.JRadioButton();
        FiltroAberto = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        filtroPor = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NomedoFuncionario.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        NomedoFuncionario.setForeground(new java.awt.Color(255, 153, 0));
        NomedoFuncionario.setText(" ");

        Table_Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table_Pedidos);

        Logout.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 153, 0));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Novo Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Pago.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        Pago.setForeground(new java.awt.Color(255, 153, 0));
        Pago.setText("Marcar como Pago");
        Pago.setEnabled(false);
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });

        FiltroPago.setText("Pago");
        FiltroPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroPagoActionPerformed(evt);
            }
        });

        FiltroAberto.setText("Aberto");
        FiltroAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroAbertoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Filtrar por");

        filtroPor.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        filtroPor.setText("jLabel2");

        voltar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 153, 0));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NomedoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(Pago)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(filtroPor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(FiltroPago)
                .addGap(28, 28, 28)
                .addComponent(FiltroAberto)
                .addGap(395, 395, 395))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(434, 434, 434))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NomedoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(Pago))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(filtroPor))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FiltroPago)
                            .addComponent(FiltroAberto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout)
                    .addComponent(voltar))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        RealizarPedidos R= new RealizarPedidos(NomedoFuncionario.getText());
        R.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
       Controladora_Pedidos P = new Controladora_Pedidos();
        int aux =Integer.parseInt(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),0).toString());
          P.Pago(aux);                                                     
                       dispose();
                       Tela_Funcionario T = new Tela_Funcionario(NomedoFuncionario.getText(),"");
                       T.setVisible(true);	
    }//GEN-LAST:event_PagoActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        TelaLogin T = new TelaLogin();
        T.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void FiltroAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroAbertoActionPerformed
       if(FiltroAberto.isSelected()){
            Tela_Funcionario T = new Tela_Funcionario(NomedoFuncionario.getText(),"ABERTO");
            T.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_FiltroAbertoActionPerformed

    private void FiltroPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroPagoActionPerformed
        if(FiltroPago.isSelected()){
            Tela_Funcionario T = new Tela_Funcionario(NomedoFuncionario.getText(),"Pago");
            T.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_FiltroPagoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_Funcionario T = new Tela_Funcionario("ADMINISTRADOR","");
                T.setVisible(true);
                T.setDefaultCloseOperation(HIDE_ON_CLOSE);
            }
        });
    }
private void carregarTabela(String S){
        ArrayList Linhas = new ArrayList<>();
        Controladora_Pedidos CP = new Controladora_Pedidos();
        String [] colunas = new String[]{"Número","Responsável","Tamanho","Massa","Ingredientes","EXTRAS","Bebida","Valor","Status"};
        for (Pedido P: CP.ListarPedidos()) {
          if(S.equals("Pago")){  
            if(P.getStatus().equals("Pago")){
            Linhas.add(new Object[]{P.getNumero_Pedido(),
                                    P.getNome_Funcionario(),
                                    P.getTamanho_Pedido(),
                                    P.getTipo_Massa(),
                                    P.getIngredientes(),
                                    P.getExtra(),
                                    P.getBebida(),
                                    "R$ "+(P.getValor_Conta()),
                                    P.getStatus()});
            }
        }
            if(S.equals("ABERTO")){
                if(P.getStatus().equals("ABERTO")){
                    Linhas.add(new Object[]{P.getNumero_Pedido(),
                                    P.getNome_Funcionario(),
                                    P.getTamanho_Pedido(),
                                    P.getTipo_Massa(),
                                    P.getIngredientes(),
                                    P.getExtra(),
                                    P.getBebida(),
                                    "R$ "+(P.getValor_Conta()),
                                    P.getStatus()});
                }
            }
            if(S.equals("")){
                Linhas.add(new Object[]{P.getNumero_Pedido(),
                                    P.getNome_Funcionario(),
                                    P.getTamanho_Pedido(),
                                    P.getTipo_Massa(),
                                    P.getIngredientes(),
                                    P.getExtra(),
                                    P.getBebida(),
                                    "R$ "+(P.getValor_Conta()),
                                    P.getStatus()});
            }
        }
        ModeloTabela  tabela = new ModeloTabela(Linhas,colunas);
        Table_Pedidos.setModel(tabela);        
        Table_Pedidos.getColumnModel().getColumn(0).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(1).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(2).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(3).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(4).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(5).setResizable(false);
        Table_Pedidos.getColumnModel().getColumn(6).setResizable(false);

        
        Table_Pedidos.getTableHeader().setReorderingAllowed(false);
      
        Table_Pedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        
        Table_Pedidos.addMouseListener(new MouseListener() {
			@Override
			public void mouseClicked(MouseEvent e) {
                            if(e.getClickCount()>1){
                                Pedido P = new Pedido();
                                P.setNumero_Pedido(Integer.parseInt(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),0).toString()));
                                P.setTamanho_Pedido(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),2).toString());
                                P.setTipo_Massa(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),3).toString());
                                P.setIngredientes(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),4).toString());
                                P.setExtra(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),5).toString());
                                P.setBebida(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),6).toString());
                                P.setValor_Conta(Double.parseDouble(Table_Pedidos.getValueAt(Table_Pedidos.getSelectedRow(),7).toString().replace("R","").replace("$","")));     
                                PedidoInfo pedido = new PedidoInfo(P);
				pedido.setVisible(true);
                            }
                            if(e.getClickCount()==1){
                                Pago.setEnabled(true);
                            }
			}

			@Override
			public void mousePressed(MouseEvent e) {
			}

			@Override
			public void mouseReleased(MouseEvent e) {
			}

			@Override
			public void mouseEntered(MouseEvent e) {
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
			}
			
		});
		
		
        
	} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FiltroAberto;
    private javax.swing.JRadioButton FiltroPago;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NomedoFuncionario;
    private javax.swing.JButton Pago;
    private javax.swing.JTable Table_Pedidos;
    private javax.swing.JLabel filtroPor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
